=== raffysommy/RestFoo/nfvInfo.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="NFV">
	<xs:complexType>
		<xs:sequence>
			<xs:element maxOccurs="1" minOccurs="1" ref="NF-FG"/>
			<xs:element ref="Hosts"/>
			<xs:element ref="Connections"/>
			<xs:element ref="VNF-Catalog"/>
		</xs:sequence>
	</xs:complexType>
	
    <xs:key name="hostKey">
      <xs:selector xpath="Hosts/Host" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:keyref name="HostNode" refer="hostKey">
      <xs:selector xpath="NF-FG/Node" />
      <xs:field xpath="@host" />
    </xs:keyref>
    <xs:keyref name="ConnectionSourceHost" refer="hostKey">
      <xs:selector xpath="Connections/Connection" />
      <xs:field xpath="@sourceHost" />
    </xs:keyref>
    <xs:keyref name="ConnectionDestHost" refer="hostKey">
      <xs:selector xpath="Connections/Connection" />
      <xs:field xpath="@destHost" />
    </xs:keyref>
    
    
	<xs:key name="F-typeKey">
      <xs:selector xpath="VNF-Catalog/F-Type" />
      <xs:field xpath="@FunctionalType" />
    </xs:key>
	<xs:keyref name="NodeF-Type" refer="F-typeKey">
      <xs:selector xpath="NF-FG/Node/F-type" />
      <xs:field xpath="@name" />
    </xs:keyref>
    
    
    <xs:key name="NF-FGname">
      <xs:selector xpath="NF-FG" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:keyref name="NF-FGNode" refer="NF-FGname">
      <xs:selector xpath="NF-FG/Node" />
      <xs:field xpath="@NF-FG" />
    </xs:keyref>
    <xs:keyref name="NF-FGLink" refer="NF-FGname">
      <xs:selector xpath="NF-FG/Link" />
      <xs:field xpath="@NF-FG" />
    </xs:keyref>
    
    
	
	<xs:unique name="LinkName">
      <xs:selector xpath="NF-FG/Link" />
      <xs:field xpath="@NF-FG" />
      <xs:field xpath="@name" />
    </xs:unique>
	
	<xs:key name="NodeName">
      <xs:selector xpath="NF-FG/Node" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:keyref name="NodeHost" refer="NodeName">
      <xs:selector xpath="Hosts/Host/NodeRef" />
      <xs:field xpath="@node" />
    </xs:keyref>
    <xs:key name="NodeLink">
      <xs:selector xpath="NF-FG/Node" />
      <xs:field xpath="@NF-FG" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:keyref name="LinkSourceNode" refer="NodeLink">
      <xs:selector xpath="NF-FG/Link" />
      <xs:field xpath="@NF-FG" />
      <xs:field xpath="@sourceNode" />
    </xs:keyref>
    <xs:keyref name="LinkDestNode" refer="NodeLink">
      <xs:selector xpath="NF-FG/Link" />
      <xs:field xpath="@NF-FG" />
      <xs:field xpath="@destNode" />
    </xs:keyref>
	
</xs:element>
<xs:element name="NF-FG">
	<xs:complexType>
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" ref="Node"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" ref="Link"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="Node">
	<xs:complexType>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="host" type="xs:string" use="optional"/>
		<xs:attribute name="NF-FG" type="xs:string" use="required"/>
		<xs:attribute name="FunctionalType" type="F-name" use="required"/>
	</xs:complexType>
</xs:element>
<xs:element name="Link">
	<xs:complexType>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="sourceNode" type="xs:string" use="required"/>
		<xs:attribute name="destNode" type="xs:string" use="required"/>
		<xs:attribute name="reqLatency" type="positiveFloat"/>
		<xs:attribute name="NF-FG" type="xs:string" use="required"/>
	</xs:complexType>
</xs:element>
<xs:element name="Hosts">
	<xs:complexType>
		<xs:sequence>
			<xs:element maxOccurs="unbounded" ref="Host"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="Host">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="NodeRef" type="NodeRefType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="diskStorage" type="positiveFloat" use="required"/>
	</xs:complexType>
</xs:element>
<xs:element name="Connections">
	<xs:complexType>
		<xs:sequence>
			<xs:element maxOccurs="unbounded" ref="Connection"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="Connection">
	<xs:complexType>
		<xs:attribute name="sourceHost" type="xs:string" use="required"/>
		<xs:attribute name="destHost" type="xs:string" use="required"/>
		<xs:attribute name="avgLatency" type="positiveFloat"/>
	</xs:complexType>
</xs:element>
<xs:element name="VNF-Catalog">
	<xs:complexType>
		<xs:sequence>
			<xs:element maxOccurs="unbounded" ref="F-Type"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="F-Type">
	<xs:complexType>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="FunctionalType" type="F-name" use="required"/>
		<xs:attribute name="reqDiskStorage" type="positiveFloat" use="required"/>
	</xs:complexType>
</xs:element>
<xs:complexType name="NodeRefType">
	<xs:attribute name="node" type="xs:string" use="required"/>
</xs:complexType>
<xs:simpleType name="F-name">
    <xs:restriction base="xs:string">
      <xs:enumeration value="CACHE"/>
      <xs:enumeration value="DPI"/>
      <xs:enumeration value="FW"/>
      <xs:enumeration value="MAIL_CLIENT"/>
      <xs:enumeration value="MAIL_SERVER"/>
      <xs:enumeration value="NAT"/> 
      <xs:enumeration value="SPAM"/>
      <xs:enumeration value="VPN"/>
      <xs:enumeration value="WEB_CLIENT"/>
      <xs:enumeration value="WEB_SERVER"/>
 	</xs:restriction>
  </xs:simpleType>
<xs:simpleType name="positiveFloat">
    <xs:restriction base="xs:float">
    	<xs:minExclusive value="0"/>
 	</xs:restriction>
  </xs:simpleType>
</xs:schema>

=== raffysommy/RestFoo/Example/xsd/nfvInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<NFV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="nfvInfo.xsd">
  <NF-FG name="nffg0">
    <Node NF-FG="nffg0" name="node0" FunctionalType="WEB_SERVER" Ip="127.0.1.3"/>
    <Node NF-FG="nffg0" name="node1" FunctionalType="WEB_CLIENT" Ip="127.0.1.5"/>
    <Node NF-FG="nffg0" name="node2" FunctionalType="FW" Ip="127.0.1.6"/>
    <Node NF-FG="nffg0" name="node3" FunctionalType="FW" Ip="127.0.1.7"/>
    <Link NF-FG="nffg0" destNode="node1" name="link0" sourceNode="node0"/>
    <Link NF-FG="nffg0" destNode="node2" name="link1" sourceNode="node1"/>
    <Link NF-FG="nffg0" destNode="node1" name="link2" sourceNode="node2"/>
  </NF-FG>
  <Hosts>
  	<Host diskStorage="10" name="host0">
  		<NodeRef node="node0"/>
  	</Host>
  	<Host diskStorage="10" name="host1">
  		<NodeRef node="node2"/>
  	</Host>
  	<Host diskStorage="30" name="host2"/>
    <Host diskStorage="10" name="host3">
  		<NodeRef node="node1"/>
  	</Host>
  	<Host diskStorage="10" name="host4">
      <NodeRef node="node2"/>
  	</Host>
  	<Host diskStorage="30" name="host5"/> 
  </Hosts>
  <Connections>
  	<Connection sourceHost="host0" destHost="host1" avgLatency ="1"/>
  	<Connection sourceHost="host1" destHost="host2" avgLatency ="2"/>	
  	<Connection sourceHost="host3" destHost="host4" avgLatency ="1"/>
  	<Connection sourceHost="host4" destHost="host5" avgLatency ="2"/>
  </Connections>
  <VNF-Catalog>
  	<VNF name="f1" FunctionalType="WEB_CLIENT" reqDiskStorage="2"/>
  	<VNF name="f2" FunctionalType="WEB_SERVER" reqDiskStorage="1"/>
  	<VNF name="f3" FunctionalType="FW" reqDiskStorage="5"/>
  	<VNF name="f4" FunctionalType="NAT" reqDiskStorage="4"/>
  	<VNF name="f5" FunctionalType="MAIL_CLIENT" reqDiskStorage="1"/>
  	<VNF name="f6" FunctionalType="MAIL_SERVER" reqDiskStorage="10"/>
  </VNF-Catalog>
</NFV>

=== raffysommy/RestFoo/Example/bin/nfvInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<NFV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="nfvInfo.xsd">
  <NF-FG name="nffg0">
    <Node NF-FG="nffg0" name="node0" FunctionalType="WEB_CLIENT" Ip="ip_1"/>
    <Node NF-FG="nffg0" name="node1" FunctionalType="FW" Ip="ip_2"/>
    <Node NF-FG="nffg0" name="node2" FunctionalType="FW" Ip="ip_3"/>
    <Node NF-FG="nffg0" name="node3" FunctionalType="WEB_SERVER" Ip="ip_4"/>
    <Link NF-FG="nffg0" sourceNode="node0" destNode="node1" name="link0"/>
    <Link NF-FG="nffg0" sourceNode="node1" destNode="node2" name="link1"/>
    <Link NF-FG="nffg0" sourceNode="node2" destNode="node3" name="link2"/>
  </NF-FG>
  <Hosts>
  	<Host diskStorage="10" name="host0">
  		<NodeRef node="node0"/>
  	</Host>
  	<Host diskStorage="10" name="host1">
  		<NodeRef node="node2"/>
  	</Host>
  	<Host diskStorage="30" name="host2"/>
    <Host diskStorage="10" name="host3">
  		<NodeRef node="node1"/>
  	</Host>
  	<Host diskStorage="10" name="host4">
      <NodeRef node="node2"/>
  	</Host>
  	<Host diskStorage="30" name="host5"/> 
  </Hosts>
  <Connections>
  	<Connection sourceHost="host0" destHost="host1" avgLatency ="1"/>
  	<Connection sourceHost="host1" destHost="host2" avgLatency ="2"/>	
  	<Connection sourceHost="host3" destHost="host4" avgLatency ="1"/>
  	<Connection sourceHost="host4" destHost="host5" avgLatency ="2"/>
  </Connections>
  <VNF-Catalog>
  	<VNF name="f1" FunctionalType="WEB_CLIENT" reqDiskStorage="2"/>
  	<VNF name="f2" FunctionalType="WEB_SERVER" reqDiskStorage="1"/>
  	<VNF name="f3" FunctionalType="FW" reqDiskStorage="5"/>
  	<VNF name="f4" FunctionalType="NAT" reqDiskStorage="4"/>
  	<VNF name="f5" FunctionalType="MAIL_CLIENT" reqDiskStorage="1"/>
  	<VNF name="f6" FunctionalType="MAIL_SERVER" reqDiskStorage="10"/>
  </VNF-Catalog>
</NFV>

=== raffysommy/RestFoo/testfile/nfvInvalid.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<NFV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nfvInfo.xsd">
    <NF-FG name="nffg0">
        <Node name="node0" NF-FG="nffg0" FunctionalType="WEB_CLIENT"/>
        <Node name="node1" NF-FG="nffg0" FunctionalType="FW" Ip="ip_2"/>
        <Node name="node2" NF-FG="nffg0" FunctionalType="FW" Ip="ip_3"/>
        <Node name="node3" NF-FG="nffg0" FunctionalType="WEB_SERVER" Ip="ip_4"/>
        <Link name="link0" sourceNode="node0" destNode="node1" NF-FG="nffg0"/>
        <Link name="link1" sourceNode="node1" destNode="node2" reqLatency="2" NF-FG="nffg0"/>
        <Link name="link2" sourceNode="node2" destNode="node3" reqLatency="2" NF-FG="nffg0"/>
    </NF-FG>
    <Hosts>
        <Host name="host0">
            <NodeRef node="node0"/>
        </Host>
        <Host name="host1" diskStorage="10.0">
            <NodeRef node="node2"/>
        </Host>
        <Host name="host2" diskStorage="3f.0"/>
        <Host name="host3" diskStorage="10.0">
            <NodeRef node="node1"/>
        </Host>
        <Host name="host4" diskStorage="10.0">
            <NodeRef node="node2"/>
        </Host>
        <Host name="host5" diskStorage="30.0"/>
    </Hosts>
    <Connections>
        <Connection sourceHost="host0" destHost="host1" avgLatency="1.0"/>
        <Connection sourceHost="host1" destHost="host2" avgLatency="2.0"/>
        <Connection sourceHost="host3" destHost="host4" avgLatency="1.0"/>
        <Connection sourceHost="host4" destHost="host5" avgLatency="2.0"/>
    </Connections>
    <VNF-Catalog>
        <VNF name="f1" FunctionalType="WEB_CLIENT" reqDiskStorage="2.0"/>
        <VNF name="f5" FunctionalType="WEB_SERVER" reqDiskStorage="1.0"/>
        <VNF name="f3" FunctionalType="FW" />
        <VNF name="f4" FunctionalType="NAT" reqDiskStorage="4.0"/>
        <VNF name="f5" FunctionalType="MAIL_CLIENT" reqDiskStorage="1.0"/>
        <VNF name="f6" FunctionalType="MAIL_SERVER" reqDiskStorage="10.0"/>
    </VNF-Catalog>
</NFV>

=== raffysommy/RestFoo/nfvInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<NFV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="nfvInfo.xsd">
  <NF-FG deployTime="2016-09-30T09:00:00" name="nffg0">
    <Node NF-FG="nffg0" name="node0" host="host0" FunctionalType="WEB_SERVER"/>
    <Node NF-FG="nffg0" name="node1" host="host0" FunctionalType="WEB_CLIENT"/>
    <Node NF-FG="nffg0" name="node2" host="host1" FunctionalType="FW"/>
    <Node NF-FG="nffg0" name="node3" FunctionalType="FW"/>
    <Link NF-FG="nffg0" reqThroughput="2" destNode="node1" name="link0" reqLatency="10" sourceNode="node0"/>
    <Link NF-FG="nffg0" destNode="node2" name="link1" sourceNode="node1"/>
    <Link NF-FG="nffg0" destNode="node1" name="link2" sourceNode="node2"/>
  </NF-FG>
  <NF-FG deployTime="2016-09-27T17:13:00" name="nffg1">
    <Node NF-FG="nffg1" name="node4" host="host3" FunctionalType="MAIL_SERVER"/>
    <Node NF-FG="nffg1" name="node5" host="host0" FunctionalType="MAIL_CLIENT"/>
    <Node NF-FG="nffg1" name="node6" host="host4" FunctionalType="FW"/>
    <Node NF-FG="nffg1" name="node7" FunctionalType="FW"/>
    <Link NF-FG="nffg1" reqThroughput="2" destNode="node5" name="link0" reqLatency="10" sourceNode="node4"/>
    <Link NF-FG="nffg1" destNode="node6" name="link1" sourceNode="node4"/>
    <Link NF-FG="nffg1" destNode="node5" name="link2" sourceNode="node7"/>
  </NF-FG>
  <Hosts>
  	<Host MaxVFN="3" diskStorage="10" memory="5" name="host0">
  		<NodeRef node="node0"/>
  		<NodeRef node="node1"/>
  		<NodeRef node="node5"/>
  	</Host>
  	<Host MaxVFN="3" diskStorage="10" memory="5" name="host1">
  		<NodeRef node="node2"/>
  	</Host>
  	<Host MaxVFN="5" diskStorage="30" memory="15" name="host2"/><Host MaxVFN="3" diskStorage="10" memory="5" name="host3">
  		<NodeRef node="node4"/>
  	</Host>
  	<Host MaxVFN="3" diskStorage="10" memory="5" name="host4">
  		<NodeRef node="node5"/>
  	</Host>
  	<Host MaxVFN="5" diskStorage="30" memory="15" name="host5"/> </Hosts>
  <Connections>
  	<Connection sourceHost="host0" destHost="host1" avgLatency ="1" avgThroughput="10"/>
  	<Connection sourceHost="host1" destHost="host2" avgLatency ="2" avgThroughput="5"/>	
  	<Connection sourceHost="host3" destHost="host4" avgLatency ="1" avgThroughput="10"/>
  	<Connection sourceHost="host4" destHost="host5" avgLatency ="2" avgThroughput="5"/>
  </Connections>
  <VNF-Catalog>
  	<F-Type name="f1" FunctionalType="WEB_CLIENT" reqMemory="1" reqDiskStorage="2"/>
  	<F-Type name="f2" FunctionalType="WEB_SERVER" reqMemory="2" reqDiskStorage="1"/>
  	<F-Type name="f3" FunctionalType="FW" reqMemory="3" reqDiskStorage="5"/>
  	<F-Type name="f4" FunctionalType="NAT" reqMemory="2" reqDiskStorage="4"/>
  	<F-Type name="f5" FunctionalType="MAIL_CLIENT" reqMemory="1" reqDiskStorage="1"/>
  	<F-Type name="f6" FunctionalType="MAIL_SERVER" reqMemory="2" reqDiskStorage="10"/>
  </VNF-Catalog>
</NFV>
