=== raffysommy/RestFoo/xsd/nfvInfo.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="NFV">
	<xs:complexType>
		<xs:sequence>
			<xs:element maxOccurs="1" minOccurs="1" ref="NF-FG"/>
			<xs:element ref="Hosts"/>
			<xs:element ref="Connections"/>
			<xs:element ref="VNF-Catalog"/>
			<xs:element name="ParsingString" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
    <xs:key name="hostKey">
      <xs:selector xpath="Hosts/Host" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:keyref name="ConnectionSourceHost" refer="hostKey">
      <xs:selector xpath="Connections/Connection" />
      <xs:field xpath="@sourceHost" />
    </xs:keyref>
    <xs:keyref name="ConnectionDestHost" refer="hostKey">
      <xs:selector xpath="Connections/Connection" />
      <xs:field xpath="@destHost" />
    </xs:keyref>
    
    
	<xs:key name="VNFKey">
      <xs:selector xpath="VNF-Catalog/VNF" />
      <xs:field xpath="@name" />
    </xs:key>
	<xs:keyref name="NodeVNF" refer="VNFKey">
      <xs:selector xpath="NF-FG/Node/VNF" />
      <xs:field xpath="@name" />
    </xs:keyref>
    
    
    <xs:key name="NF-FGname">
      <xs:selector xpath="NF-FG" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:keyref name="NF-FGNode" refer="NF-FGname">
      <xs:selector xpath="NF-FG/Node" />
      <xs:field xpath="@NF-FG" />
    </xs:keyref>
    <xs:keyref name="NF-FGLink" refer="NF-FGname">
      <xs:selector xpath="NF-FG/Link" />
      <xs:field xpath="@NF-FG" />
    </xs:keyref>
    
    
	
	<xs:unique name="IpAddress">
      <xs:selector xpath="NF-FG/Node" />
      <xs:field xpath="@Ip" />
    </xs:unique>
	<xs:unique name="LinkName">
      <xs:selector xpath="NF-FG/Link" />
      <xs:field xpath="@NF-FG" />
      <xs:field xpath="@name" />
    </xs:unique>
	
	<xs:key name="NodeName">
      <xs:selector xpath="NF-FG/Node" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:keyref name="NodeHost" refer="NodeName">
      <xs:selector xpath="Hosts/Host/NodeRef" />
      <xs:field xpath="@node" />
    </xs:keyref>
    <xs:key name="NodeLink">
      <xs:selector xpath="NF-FG/Node" />
      <xs:field xpath="@NF-FG" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:keyref name="LinkSourceNode" refer="NodeLink">
      <xs:selector xpath="NF-FG/Link" />
      <xs:field xpath="@NF-FG" />
      <xs:field xpath="@sourceNode" />
    </xs:keyref>
    <xs:keyref name="LinkDestNode" refer="NodeLink">
      <xs:selector xpath="NF-FG/Link" />
      <xs:field xpath="@NF-FG" />
      <xs:field xpath="@destNode" />
    </xs:keyref>
	
</xs:element>
<xs:element name="NF-FG">
	<xs:complexType>
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" ref="Node"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" ref="Link"/>
			<xs:element name="Property" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="Node">
	<xs:complexType>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="NF-FG" type="xs:string" use="required"/>
		<xs:attribute name="VNF" type="xs:string" use="required"/>
		<xs:attribute name="Ip" type="xs:string" use="required"/>	
	</xs:complexType>
</xs:element>
<xs:element name="Link">
	<xs:complexType>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="sourceNode" type="xs:string" use="required"/>
		<xs:attribute name="destNode" type="xs:string" use="required"/>
		<xs:attribute name="reqLatency" type="xs:int" use="required"/>
		<xs:attribute name="NF-FG" type="xs:string" use="required"/>
	</xs:complexType>
</xs:element>
<xs:element name="Hosts">
	<xs:complexType>
		<xs:sequence>
			<xs:element maxOccurs="unbounded" ref="Host"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="Host">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="NodeRef" type="NodeRefType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="diskStorage" type="positiveFloat" use="required"/>
	</xs:complexType>
</xs:element>
<xs:element name="Connections">
	<xs:complexType>
		<xs:sequence>
			<xs:element maxOccurs="unbounded" ref="Connection"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="Connection">
	<xs:complexType>
		<xs:attribute name="sourceHost" type="xs:string" use="required"/>
		<xs:attribute name="destHost" type="xs:string" use="required"/>
		<xs:attribute name="avgLatency" type="positiveFloat"/>
	</xs:complexType>
</xs:element>
<xs:element name="VNF-Catalog">
	<xs:complexType>
		<xs:sequence>
			<xs:element maxOccurs="unbounded" ref="VNF"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="VNF">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Configuration" type="ConfigurationType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="FunctionalType" type="F-name" use="required"/>
		<xs:attribute name="reqDiskStorage" type="positiveFloat" use="required"/>
	</xs:complexType>
</xs:element>
<xs:complexType name="NodeRefType">
	<xs:attribute name="node" type="xs:string" use="required"/>
</xs:complexType>
<xs:simpleType name="F-name">
    <xs:restriction base="xs:string">
      <xs:enumeration value="FW"/>
      <xs:enumeration value="CLASSIFIER"/>
      <xs:enumeration value="DUMB"/>
      <xs:enumeration value="ENDHOST"/>
      <xs:enumeration value="SPAM"/>
      <xs:enumeration value="CACHE"/>
      <xs:enumeration value="IDS"/>
      <xs:enumeration value="MAIL_CLIENT"/>
      <xs:enumeration value="MAIL_SERVER"/>
      <xs:enumeration value="NAT"/>
      <xs:enumeration value="VPN"/>
      <xs:enumeration value="WEB_CLIENT"/>
      <xs:enumeration value="WEB_SERVER"/>
 	</xs:restriction>
  </xs:simpleType>
<xs:simpleType name="positiveFloat">
    <xs:restriction base="xs:float">
    	<xs:minExclusive value="0"/>
 	</xs:restriction>
</xs:simpleType>
<xs:complexType name="ConfigurationType">
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
</xs:complexType>
</xs:schema>

=== raffysommy/RestFoo/xsd/nfvInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<NFV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="nfvInfo.xsd">
  <NF-FG name="nffg0">
    <Node NF-FG="nffg0" name="node0" VNF="f1" Ip="ip_0"/>
    <Node NF-FG="nffg0" name="node1" VNF="f3" Ip="ip_1"/>
    <Node NF-FG="nffg0" name="node2" VNF="f7" Ip="ip_2"/>
    <Node NF-FG="nffg0" name="node3" VNF="f3" Ip="ip_3"/>
    <Node NF-FG="nffg0" name="node4" VNF="f2" Ip="ip_4"/>
    <Link NF-FG="nffg0" sourceNode="node0" destNode="node1" reqLatency="10" name="link0"/>
    <Link NF-FG="nffg0" sourceNode="node1" destNode="node3" reqLatency="20" name="link1"/>
    <Link NF-FG="nffg0" sourceNode="node3" destNode="node4" reqLatency="30" name="link2"/>
    <Link NF-FG="nffg0" sourceNode="node1" destNode="node2" reqLatency="30" name="link3"/>
    <Link NF-FG="nffg0" sourceNode="node2" destNode="node4" reqLatency="30" name="link4"/>
  </NF-FG>
  <Hosts>
  	<Host diskStorage="10" name="host0">
  		<NodeRef node="node0"/>
  	</Host>
  	<Host diskStorage="10" name="host1">
  		<NodeRef node="node2"/>
  	</Host>
  	<Host diskStorage="30" name="host2"/>
    <Host diskStorage="10" name="host3">
  		<NodeRef node="node1"/>
  	</Host>
  	<Host diskStorage="10" name="host4">
      <NodeRef node="node2"/>
  	</Host>
  	<Host diskStorage="30" name="host5"/> 
  </Hosts>
  <Connections>
  	<Connection sourceHost="host0" destHost="host1" avgLatency ="1"/>
  	<Connection sourceHost="host1" destHost="host2" avgLatency ="2"/>	
  	<Connection sourceHost="host3" destHost="host4" avgLatency ="1"/>
  	<Connection sourceHost="host4" destHost="host5" avgLatency ="2"/>
  </Connections>
  <VNF-Catalog>
  	<VNF name="f1" FunctionalType="WEB_CLIENT" reqDiskStorage="2"/>
  	<VNF name="f2" FunctionalType="WEB_SERVER" reqDiskStorage="1"/>
  	<VNF name="f3" FunctionalType="FW" reqDiskStorage="5">
  		<Configuration name="ip_0" value="ip_4"/>
  	</VNF>
  	<VNF name="f4" FunctionalType="NAT" reqDiskStorage="4"/>
  	<VNF name="f5" FunctionalType="MAIL_CLIENT" reqDiskStorage="1"/>
  	<VNF name="f6" FunctionalType="MAIL_SERVER" reqDiskStorage="10"/>
  	<VNF name="f7" FunctionalType="IDS" reqDiskStorage="3"/>
  </VNF-Catalog>
</NFV>

=== raffysommy/RestFoo/testfile/nfvIn.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<NFV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nfvInfo.xsd">
    <NF-FG name="nffg0">
        <Node name="node0" NF-FG="nffg0" VNF="f1" Ip="ip_0"/>
        <Node name="node1" NF-FG="nffg0" VNF="f3" Ip="ip_1"/>
        <Node name="node2" NF-FG="nffg0" VNF="f7" Ip="ip_2"/>
        <Node name="node3" NF-FG="nffg0" VNF="f3" Ip="ip_3"/>
        <Node name="node4" NF-FG="nffg0" VNF="f2" Ip="ip_4"/>
        <Link name="link0" sourceNode="node0" destNode="node1" reqLatency="10" NF-FG="nffg0"/>
        <Link name="link1" sourceNode="node1" destNode="node3" reqLatency="20" NF-FG="nffg0"/>
        <Link name="link2" sourceNode="node3" destNode="node4" reqLatency="30" NF-FG="nffg0"/>
        <Link name="link3" sourceNode="node1" destNode="node2" reqLatency="30" NF-FG="nffg0"/>
        <Link name="link4" sourceNode="node2" destNode="node4" reqLatency="30" NF-FG="nffg0"/>
    </NF-FG>
    <Hosts>
        <Host name="host0" diskStorage="10.0">
            <NodeRef node="node0"/>
        </Host>
        <Host name="host1" diskStorage="10.0">
            <NodeRef node="node2"/>
        </Host>
        <Host name="host2" diskStorage="30.0"/>
        <Host name="host3" diskStorage="10.0">
            <NodeRef node="node1"/>
        </Host>
        <Host name="host4" diskStorage="10.0">
            <NodeRef node="node2"/>
        </Host>
        <Host name="host5" diskStorage="30.0"/>
    </Hosts>
    <Connections>
        <Connection sourceHost="host0" destHost="host1" avgLatency="1.0"/>
        <Connection sourceHost="host1" destHost="host2" avgLatency="2.0"/>
        <Connection sourceHost="host3" destHost="host4" avgLatency="1.0"/>
        <Connection sourceHost="host4" destHost="host5" avgLatency="2.0"/>
    </Connections>
    <VNF-Catalog>
        <VNF name="f1" FunctionalType="WEB_CLIENT" reqDiskStorage="2.0"/>
        <VNF name="f2" FunctionalType="WEB_SERVER" reqDiskStorage="1.0"/>
        <VNF name="f3" FunctionalType="FW" reqDiskStorage="5.0">
            <Configuration name="ip_0" value="ip_4"/>
        </VNF>
        <VNF name="f4" FunctionalType="NAT" reqDiskStorage="4.0"/>
        <VNF name="f5" FunctionalType="MAIL_CLIENT" reqDiskStorage="1.0"/>
        <VNF name="f6" FunctionalType="MAIL_SERVER" reqDiskStorage="10.0"/>
        <VNF name="f7" FunctionalType="IDS" reqDiskStorage="3.0"/>
    </VNF-Catalog>
</NFV>
